---
- name: This is playbook to demonstrate the use of host-variables
  hosts: ansible-c-4572-vm-1
  # Creating Tasks
  tasks:
  # Task 1
    - name: Installing the {{ package1 }} and {{package2}} packages
      dnf:
        name:
        - "{{ package1 }}"
        - "{{ package2 }}"
        state: present 
      register: installation_output
  # Task 2 
    - name: Displaying entire output
      debug:
        var: installation_output  
  # Task 3 
    - name: Displaying the name of packages that were installed
      debug:
        msg: 
          - The following packages were installed - 
          - "{{ installation_output['results'] }}" 